### ISSUE TITLE
Automatic check for newer plugin versions

### ISSUE THREAD

**Issue by tobi18991** [INCYDE-GmbH/drawio-plugin-attackgraphs#122]
Include a function into the plugin that checks on GitHub whether a newer version (release) of the plugin is available and show the result to the user.

The check shall only be initiated when draw.io is started (plugin gets loaded). Furthermore, the information dialog shall only be presented when a newer version is available. The dialog shall include an option to download the latest release, an option to dismiss the message, and an option to dismiss and never be remindeded again except an even newever version was released.

**Comment by Mq89** [comment]
Check always fails with the following error message in draw.io Desktop:
![grafik](https://user-images.githubusercontent.com/4853357/231250015-e5e63e16-6187-4681-b6cd-95eb52b7f2b4.png)

**Comment by tobi18991** [comment]
The problem seems to be related to the `Content-Security-Policy` set by the draw.io desktop version. It does not include calls to `https://api.github.com`.

Maybe I will find a way around that problem. Otherwise, as the CSP is not in our control, I might have to remove the automatic update check from the plugin...

**Comment by tobi18991** [comment]
I found a way around the CSP issue. The newest release version is now fetched using [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers). Luckily, Web Workers are not affected by the CSP of the document creating the worker. 

Therefore, it should work now also for the desktop version. I will create a PR now to merge the changes into the `main` branch.
