### ISSUE TITLE
Include option to separate functions from .drawio file

### ISSUE THREAD

**Issue by RichardPoschingerINCYDE** [INCYDE-GmbH/drawio-plugin-attackgraphs#132]
### Proposal
It might be beneficial for pre-defined (written by the plugin authors) functions to be separated from the .drawio file (and its graph). The function definition could be included in the release file of the plugin.

### Options
This could result in the following options:
- Pre-defined function:
  - Internal function file
  - .drawio file referring to the function definition
- User-defined function:
  - .drawio file including the function definition

### Advantage:
- Functions can be updated to provide improvements of bugfixes (affects especially long-term projects)
- Error prone copy-paste process during function updates is eliminated

**Comment by Mq89** [comment]
I do understand your point. But I would like to keep the abstract concept (graphs and aggregation) apart from the concrete methodology (attributes from 50701, RKL and 21434 (in the future)).

Currently, I use the templates as reference for the latest version of the functions.

Maybe we can ship the functions (including maybe multiple versions of them) in separate files and provide an "update functions" feature where the user can easily select the desired update file of the functions to avoid manual copy-paste.

**Comment by RichardPoschingerINCYDE** [comment]
Sounds like a good alternative solution!
