### ISSUE TITLE
AttackGraph not starting in Draw.io 21.5.0

### ISSUE THREAD

**Issue by RichardPoschingerINCYDE** [INCYDE-GmbH/drawio-plugin-attackgraphs#141]
The AttackGraph Plugin (current release) seems not be starting in draw.io Desktop version **21.5.0**.
The AttackGraph menu is not showing up, even if the plugin is newly added to draw.io.

**Comment by tobi18991** [comment]
Thanks for reporting this issue! It seems that this is an issue of the current version (v21.5.0) of [drawio-desktop](https://github.com/jgraph/drawio-desktop). The commit [6462429](https://github.com/jgraph/drawio-desktop/commit/64624299e0b5b99d45b577d2c9842dc559a44b0e) resolves it and will be included in the release of version [21.5.1](https://github.com/jgraph/drawio-desktop/releases/tag/v21.5.1).

When the newer version of drawio-desktop is released, I will close this issue.

**Comment by tobi18991** [comment]
The new version is out now: [v21.5.1](https://github.com/jgraph/drawio-desktop/releases/tag/v21.5.1)
