### ISSUE TITLE
Template import/export string can be misleading

### ISSUE THREAD

**Issue by Mq89** [INCYDE-GmbH/drawio-plugin-attackgraphs#156]
The string presented to the user to import (and export) templates can be misleading.

![grafik](https://github.com/user-attachments/assets/03b8375a-894d-4de6-bed4-e39acffc3e6e)

Users could try to import full graph templates (`.drawio`) instead of the function templates (`.json`) and face the following error message:

![grafik](https://github.com/user-attachments/assets/869286a7-76ef-4e2e-9347-342240620792)

Possible mitigations:
- Ensure that the opening `ImportFileDialog` only accepts `.json` files.
- Rename the strings (English and German) to something like "Import Function Template...".
- Rename the templates provided in the repository from `AttackGraphTemplate_TS50701.json` to `AttackGraphFunctionTemplate_TS50701.json`.

**Comment by tobi18991** [comment]
Closes by #163
