### ISSUE TITLE
Default attributes with default values trigger comparison in non-leave nodes

### ISSUE THREAD

**Issue by Mq89** [INCYDE-GmbH/drawio-plugin-attackgraphs#16]
The plugin conveniently adds some templates already containing the configured default attributes to draw.io's sidebar.

![grafik](https://user-images.githubusercontent.com/4853357/156529391-4913f822-477e-473d-9411-b3b25b21903d.png)

However, also non-leave nodes (currently, only the one marked in the figure) have the default attributes pre-configured which disturbes the workflow of creating an attack graph. If non-leave nodes have attributes and the attributes have default values configured, the comparison is unnecessarily activated.

![grafik](https://user-images.githubusercontent.com/4853357/156539797-d7cc463e-3442-4913-89ef-e5c2c5cc92b3.png)

<details>
<summary>Example Graph</summary>

```xml
<mxGraphModel dx="1102" dy="857" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="583" pageHeight="827" math="0" shadow="0">
  <root>
    <object id="0">
      <ag_global_attributes>
        <ag_global_attribute name="Testattribut" value="0" iconName="" min="0" max="4" />
      </ag_global_attributes>
      <ag_attributes />
      <ag_computed_attributes />
      <mxCell />
    </object>
    <object id="1">
      <ag_attributes />
      <ag_computed_attributes />
      <mxCell parent="0" />
    </object>
    <object label="Activity" Testattribut="3" id="tVLiphedjEk2YKl1oAa3-1">
      <ag_attributes />
      <ag_computed_attributes />
      <mxCell style="shape=attackgraphs.node;" parent="1" vertex="1">
        <mxGeometry x="210" y="250" width="150" height="75" as="geometry" />
      </mxCell>
    </object>
    <object id="tVLiphedjEk2YKl1oAa3-3">
      <ag_attributes />
      <ag_computed_attributes />
      <mxCell style="rounded=0;orthogonalLoop=1;jettySize=auto;html=1;strokeWidth=2;" parent="1" source="tVLiphedjEk2YKl1oAa3-4" target="tVLiphedjEk2YKl1oAa3-1" edge="1">
        <mxGeometry relative="1" as="geometry" />
      </mxCell>
    </object>
    <object label="Activity" Testattribut="0" id="tVLiphedjEk2YKl1oAa3-4">
      <ag_attributes Testattribut="3" />
      <ag_computed_attributes />
      <ag_aggregation_custom_function ag_aggregation_custom_function="function(c){&#xa;    var result = 0;&#xa;    c.childAttributes.forEach(function(child){&#xa;        result += parseInt(child.attributes[&quot;Testattribut&quot;]);&#xa;    })&#xa;    return {&quot;Testattribut&quot;: result};&#xa;}" />
      <mxCell style="shape=attackgraphs.node;" vertex="1" parent="1">
        <mxGeometry x="210" y="130" width="150" height="75" as="geometry" />
      </mxCell>
    </object>
  </root>
</mxGraphModel>
```
</details>

**Comment by tobi18991** [comment]
@Mq89 What is your proposed solution to this issue? Should default values not be inserted when dragging a new node into the diagram? Right now, the comparison is only triggered because of your custom function which calculates an aggregation of the child attributes.

Or shall comparisons not be triggered if all attributes have a default value?

**Comment by Mq89** [comment]
One option would be to not put default attributes in this particular template (the white) and leave the other templates (green, yellow etc.) as they are.

**Comment by tobi18991** [comment]
Okay, I'm on it.
