### ISSUE TITLE
Highlight critical paths

### ISSUE THREAD

**Issue by Mq89** [INCYDE-GmbH/drawio-plugin-attackgraphs#57]
The child node of each node that is currently responsible for the worst risk should be highlighted or highlightable.
This could be done by drawing the respective edge thicker or in a different color (coordinate with #58), or draw the child node with a thicker border.
Responsibility is only valid for some logical connections (e.g., OR. For AND it does not make sense as all child nodes contribute to the risk semantically).
Responsibility is determined by the aggregation function, thus somehow the API would change to tell Drawio from the aggregation function which edge (or child node) to highlight (is there a way around that?).

**Comment by Mq89** [comment]
@SimonUngerUniPassau Feel free to contribute ideas.

**Comment by tobi18991** [comment]
> [...] Responsibility is determined by the aggregation function, thus somehow the API would change to tell Drawio from the aggregation function which edge (or child node) to highlight (is there a way around that?).

@Mq89 I guess there won't be any way arround changing the API. Functions are executed in the interpreter and the return values either contain an object with the aggregated attributes for a node or a value for the node's computed attribute. Hence, signaling new information (in our case highlighting nodes/edges) will definitely need a change to the API, e.g., expecting an attribute in the returned object.

However, maybe someone else has a different opinion?
