### ISSUE TITLE
Check interference when resizeing or moving a node

### ISSUE THREAD

**Issue by Mq89** [INCYDE-GmbH/drawio-plugin-attackgraphs#75]
Resizing and moving attack graph nodes can be very slow in sufficiently large graphs with aggregation functions to be evaluated.

My uneducated guess is that recalculations or redrawings are triggered to often. Eg., every time the node is moved by 1px (which would be unnecessary).
Please have a look at the code. Maybe you can find a cause for the behaviour.

A strategy could also be to be more conservative with triggering recalculations and instead provide a context menu option to force calculations.

**Comment by tobi18991** [comment]
@Mq89 Simply moving the refresh statement out of the loop improved the performance. If you want you can try it out with a larger graph but for me the time needed to move nodes was definitely faster with the implemented change.

I already included the update in the main branch.
