### ISSUE TITLE
Start a Changelog and versioning

### ISSUE THREAD

**Issue by Mq89** [INCYDE-GmbH/drawio-plugin-attackgraphs#85]
As more and more features keep beeing added, should we start keeping a changelog and introduce version numbers?

@tobi18991 

If we do, this is the relevant reference:
- https://keepachangelog.com/en/1.0.0/
- https://semver.org/

We should then extend the contex menu to present the version number in addition to the commit hash.

**Comment by tobi18991** [comment]
Good idea! As version numbers are more comprehensible for humans than commit hashes, this would probably help users to check whether a new version of the plugin is available. Therefore, we could use the release feature of GitHub and, for example, attach the accompanying `attackgraphs.js` file to each release. (Maybe we can also introduce a version check in the plugin itself and notify the user in case of a newer version available.)
