### ISSUE TITLE
Enlarge Bubble Size 

### ISSUE THREAD

**Issue by JR-XR** [INCYDE-GmbH/drawio-plugin-attackgraphs#89]
Enlarge bubble size of the score/value, bubblediameter = 40.

**Comment by Mq89** [comment]
What is the current value and how would it look like with the increased diameter?

**Comment by JR-XR** [comment]
Current should be 20, 40 should work.

**Comment by tobi18991** [comment]
I changed the code for the size of the computed attributes batch. The width of the batch now depends on the width of the text displayed in it. Therefore, the displayed text does not overflow batches anymore.

For more information see the corresponding PR: #95
